// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation  OperationName = "CreateUser"
	GetImageOperation    OperationName = "GetImage"
	GetUserOperation     OperationName = "GetUser"
	ListImagesOperation  OperationName = "ListImages"
	ListUsersOperation   OperationName = "ListUsers"
	UploadImageOperation OperationName = "UploadImage"
)
