// Code generated by ogen, DO NOT EDIT.

package api

import (
	ht "github.com/ogen-go/ogen/http"
)

// Ref: #/components/schemas/Image
type Image struct {
	ID   string `json:"id"`
	URL  string `json:"url"`
	Size int    `json:"size"`
}

// GetID returns the value of ID.
func (s *Image) GetID() string {
	return s.ID
}

// GetURL returns the value of URL.
func (s *Image) GetURL() string {
	return s.URL
}

// GetSize returns the value of Size.
func (s *Image) GetSize() int {
	return s.Size
}

// SetID sets the value of ID.
func (s *Image) SetID(val string) {
	s.ID = val
}

// SetURL sets the value of URL.
func (s *Image) SetURL(val string) {
	s.URL = val
}

// SetSize sets the value of Size.
func (s *Image) SetSize(val int) {
	s.Size = val
}

// NewOptMultipartFile returns new OptMultipartFile with value set to v.
func NewOptMultipartFile(v ht.MultipartFile) OptMultipartFile {
	return OptMultipartFile{
		Value: v,
		Set:   true,
	}
}

// OptMultipartFile is optional ht.MultipartFile.
type OptMultipartFile struct {
	Value ht.MultipartFile
	Set   bool
}

// IsSet returns true if OptMultipartFile was set.
func (o OptMultipartFile) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMultipartFile) Reset() {
	var v ht.MultipartFile
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMultipartFile) SetTo(v ht.MultipartFile) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMultipartFile) Get() (v ht.MultipartFile, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMultipartFile) Or(d ht.MultipartFile) ht.MultipartFile {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type UploadImageReq struct {
	File OptMultipartFile `json:"file"`
}

// GetFile returns the value of File.
func (s *UploadImageReq) GetFile() OptMultipartFile {
	return s.File
}

// SetFile sets the value of File.
func (s *UploadImageReq) SetFile(val OptMultipartFile) {
	s.File = val
}

// Ref: #/components/schemas/User
type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// GetID returns the value of ID.
func (s *User) GetID() string {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() string {
	return s.Email
}

// SetID sets the value of ID.
func (s *User) SetID(val string) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val string) {
	s.Email = val
}
