// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	ImagesHandler
	UsersHandler
}

// ImagesHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Images
type ImagesHandler interface {
	// GetImage implements getImage operation.
	//
	// Get an image by ID.
	//
	// GET /images/{id}
	GetImage(ctx context.Context, params GetImageParams) (*Image, error)
	// ListImages implements listImages operation.
	//
	// List all images.
	//
	// GET /images
	ListImages(ctx context.Context) ([]Image, error)
	// UploadImage implements uploadImage operation.
	//
	// Upload a new image.
	//
	// POST /images
	UploadImage(ctx context.Context, req *UploadImageReq) (*Image, error)
}

// UsersHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Users
type UsersHandler interface {
	// CreateUser implements createUser operation.
	//
	// Create a new user.
	//
	// POST /users
	CreateUser(ctx context.Context, req *User) (*User, error)
	// GetUser implements getUser operation.
	//
	// Get a user by ID.
	//
	// GET /users/{id}
	GetUser(ctx context.Context, params GetUserParams) (*User, error)
	// ListUsers implements listUsers operation.
	//
	// List all users.
	//
	// GET /users
	ListUsers(ctx context.Context) ([]User, error)
}

// ImagesServer implements http server based on OpenAPI v3 specification and
// calls ImagesHandler to handle requests.
type ImagesServer struct {
	h ImagesHandler
	baseServer
}

// NewImagesServer creates new ImagesServer.
func NewImagesServer(h ImagesHandler, opts ...ServerOption) (*ImagesServer, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &ImagesServer{
		h:          h,
		baseServer: s,
	}, nil
}

// UsersServer implements http server based on OpenAPI v3 specification and
// calls UsersHandler to handle requests.
type UsersServer struct {
	h UsersHandler
	baseServer
}

// NewUsersServer creates new UsersServer.
func NewUsersServer(h UsersHandler, opts ...ServerOption) (*UsersServer, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &UsersServer{
		h:          h,
		baseServer: s,
	}, nil
}
