// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedImagesHandler is no-op ImagesHandler which returns http.ErrNotImplemented.
type UnimplementedImagesHandler struct{}

var _ ImagesHandler = UnimplementedImagesHandler{}

// GetImage implements getImage operation.
//
// Get an image by ID.
//
// GET /images/{id}
func (UnimplementedImagesHandler) GetImage(ctx context.Context, params GetImageParams) (r *Image, _ error) {
	return r, ht.ErrNotImplemented
}

// ListImages implements listImages operation.
//
// List all images.
//
// GET /images
func (UnimplementedImagesHandler) ListImages(ctx context.Context) (r []Image, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadImage implements uploadImage operation.
//
// Upload a new image.
//
// POST /images
func (UnimplementedImagesHandler) UploadImage(ctx context.Context, req *UploadImageReq) (r *Image, _ error) {
	return r, ht.ErrNotImplemented
}

// UnimplementedUsersHandler is no-op UsersHandler which returns http.ErrNotImplemented.
type UnimplementedUsersHandler struct{}

var _ UsersHandler = UnimplementedUsersHandler{}

// CreateUser implements createUser operation.
//
// Create a new user.
//
// POST /users
func (UnimplementedUsersHandler) CreateUser(ctx context.Context, req *User) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Get a user by ID.
//
// GET /users/{id}
func (UnimplementedUsersHandler) GetUser(ctx context.Context, params GetUserParams) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// List all users.
//
// GET /users
func (UnimplementedUsersHandler) ListUsers(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}
